name: Auto Format
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
# Need write permissions to commit formatting changes
permissions:
  contents: write
  pull-requests: write
jobs:
  auto-format:
    # Skip if the commit message contains [skip-format] to avoid loops
    if: "!contains(github.event.head_commit.message, '[skip-format]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Use GitHub token with write access
          token: ${{ secrets.GITHUB_TOKEN }}
          # For pull requests, checkout the head ref
          ref: ${{ github.head_ref || github.ref }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Install dependencies
        run: go mod download
      - name: Run format
        run: make fmt
      - name: Check for changes
        id: check-changes
        run: |
          if git diff --quiet; then
            echo "no-changes=true" >> $GITHUB_OUTPUT
          else
            echo "no-changes=false" >> $GITHUB_OUTPUT
          fi
      - name: Commit changes
        if: steps.check-changes.outputs.no-changes == 'false'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "chore: auto-format code [skip-format]

          Automatically formatted by GitHub Actions.

          Co-authored-by: Yosuke Akatsuka <pankona@users.noreply.github.com>"
      - name: Push changes
        if: steps.check-changes.outputs.no-changes == 'false'
        run: |-
          # For pull requests, push to the head branch
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            git push origin HEAD:${{ github.head_ref }}
          else
            git push origin ${{ github.ref_name }}
          fi
